const fs = require("fs");
const path = require("path");
const vm = require("vm");

const repoRoot = path.resolve(__dirname, "..");
const outPath = path.join(repoRoot, "PROJECT_HEALTH.md");

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

function exists(relativePath) {
  return fs.existsSync(path.join(repoRoot, relativePath));
}

function loadFormulaData() {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(read("handbook/formula-data.js"), sandbox, { filename: "formula-data.js" });
  return {
    cards: sandbox.window.FORMULA_CARDS || [],
    groups: sandbox.window.FORMULA_GROUPS || [],
    references: sandbox.window.FORMULA_SOURCE_REFERENCES || []
  };
}

function countBy(items, selector) {
  const counts = new Map();
  for (const item of items) {
    const key = selector(item);
    counts.set(key, (counts.get(key) || 0) + 1);
  }
  return counts;
}

function table(headers, rows) {
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map((cell) => String(cell).replace(/\|/g, "\\|")).join(" | ")} |`)
  ].join("\n");
}

function main() {
  const pkg = JSON.parse(read("package.json"));
  const { cards, groups, references } = loadFormulaData();
  const interactiveCards = cards.filter((card) => card.interactiveType && card.interactiveType !== "none");
  const labTypes = countBy(interactiveCards, (card) => card.interactiveType);
  const subjects = countBy(cards, (card) => card.subject);
  const importance = countBy(cards, (card) => card.importance);

  const governanceFiles = [
    "README.md",
    "CONTRIBUTING.md",
    "CONTENT_GOVERNANCE.md",
    "ACCESSIBILITY.md",
    "PRIVACY.md",
    "SECURITY.md",
    "VERSIONING.md",
    "CHANGELOG.md",
    "CITATION.cff",
    "COVERAGE.md",
    "PROJECT_HEALTH.md"
  ];

  const checks = [
    ["Base verification", "`npm run verify`", "Syntax, data, generated docs, coverage, smoke, quality, links, hygiene, Pages artifact"],
    ["Environment doctor", "`npm run doctor`", "Checks required files, Node version, and optional local tools such as Playwright and GitHub CLI"],
    ["Browser smoke", "`npm run verify:browser`", "Real Chromium desktop/mobile/lab interaction checks"],
    ["Live smoke", "`npm run verify:browser:live`", "Runs browser smoke against GitHub Pages"],
    ["Deploy audit", "`npm run verify:deploy`", "Checks live versioned assets and Pages deployment health"]
  ];

  const lines = [
    "# Project Health",
    "",
    "> Generated by `node handbook/project-health.js`. Do not edit this file by hand.",
    "",
    "## Release Snapshot",
    "",
    table(
      ["Metric", "Value"],
      [
        ["Package", pkg.name],
        ["Version", pkg.version],
        ["License", pkg.license],
        ["Homepage", pkg.homepage],
        ["Node", pkg.engines?.node || "unspecified"],
        ["Formula cards", cards.length],
        ["Interactive card bindings", interactiveCards.length],
        ["Interactive lab types", labTypes.size],
        ["Subject groups", groups.length],
        ["Source references", references.length]
      ]
    ),
    "",
    "## Subject Coverage",
    "",
    table(
      ["Subject", "Cards"],
      [...subjects.entries()].map(([subject, count]) => [subject, count])
    ),
    "",
    "## Importance Mix",
    "",
    table(
      ["Importance", "Cards"],
      ["必背", "常用", "技巧", "了解", "拓展"].map((key) => [key, importance.get(key) || 0])
    ),
    "",
    "## Interactive Lab Coverage",
    "",
    table(
      ["interactiveType", "Bound Cards"],
      [...labTypes.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([type, count]) => [type, count])
    ),
    "",
    "## Verification Surface",
    "",
    table(["Area", "Command", "Coverage"], checks),
    "",
    "## Governance Files",
    "",
    table(
      ["File", "Status"],
      governanceFiles.map((file) => [file, exists(file) ? "present" : "missing"])
    ),
    "",
    "## Health Gate",
    "",
    cards.length >= 490 &&
    interactiveCards.length >= 180 &&
    labTypes.size >= 15 &&
    governanceFiles.every(exists)
      ? "PASS: project maturity health gate satisfied."
      : "FAIL: project maturity health gate is not satisfied.",
    ""
  ];

  fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");
  console.log(`project-health-ok cards=${cards.length} interactive=${interactiveCards.length} labTypes=${labTypes.size} report=PROJECT_HEALTH.md`);
}

main();
